name: product_overview
description: "Flutter Web Product Overview - Recruitment Task"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  dio: ^5.7.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^14.6.2

  # Image Caching
  cached_network_image: ^3.4.1

  # JSON Serialization
  json_annotation: ^4.9.0
  skeletonizer: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
